Updated cv_install_clusterbats to nodeset nodes as well.

diff --git a/controller/rootimg/install/postscripts/cv_fly_clusterbats b/controller/rootimg/install/postscripts/cv_fly_clusterbats
--- a/controller/rootimg/install/postscripts/cv_fly_clusterbats
+++ b/controller/rootimg/install/postscripts/cv_fly_clusterbats
@@ -2,29 +2,37 @@
 ##title          : cv_fly_clusterbats
 ##description    : Automatically test controller installation and deploys the cluster. 
 ##                 You need to edit the params file in /trinity/testing. (to be writter)
-##author         : Themis Athanassiaodu
+##author         : Themis Athanassiadou
 ##email          : themis.athanassiadou@clustervision.com
 
 # Install the the Bash Automated Testing System:
-sh /trinity/testing/install_bats.sh
+if [ ! -d "/trinity/testing/bats" ]; then
+   sh /trinity/testing/install_bats.sh
+fi
 
 # Run the controller bats for test case 1.1
 bats /trinity/testing/clusterbats/t1.1.bats
 
-# Add an if to test if all the test pass
+#Outcome of test: if 0, all tests pass, and can proceed.
+outcome="$(echo $?)"
+[[ "$outcome" -eq 0 ]] && { echo "controller passed! proceed"; } || { echo "the controller did not pass all tests, exiting"; exit 1; }
 
 
 #Configure xcat tables to deploy cluster 
 ##FIXME make environment variables and define in different file.
 source /etc/profile.d/xcat.sh
 
+#ip_current="$(gettab node=switch hosts.ip)"
+#echo $(ip_current) 
 chtab node=switch hosts.ip=10.141.253.1
 chtab switch=switch switch.node=compute
-chtab switch=switch switch.port="|\D+(\d+)|fa($1+0)|"
+chtab switch=switch switch.port="|\D+(\d+)|fa(\$1+0)|"
 makehosts switch
 makedns switch
 
 # do a switch ping test before proceeding
+# test?
+ping -c 1 switch &> /dev/null && { echo "can ping switch, proceed"; } || { echo "Cannot ping switch, exiting"; exit 1; }
 
 nodeadd node[001-003] groups=compute
 makehosts compute
@@ -36,12 +44,34 @@ makedns vc-a
 
 mkdef -t group -o hw-GenericNodes members=c001,c002
 
+
+
 #reboot nodes so they go into genesis
 rpower node001-node003 reset
 #need to make sure no error
 
-#make sure they go into genesis
-#while ! ssh node uname -a; do sleep 1; done
+sleep 10 
+
+#make sure they go into genesis/ssh (node001 usually slow - need to add multiple node checks)
+#while ! ssh node001; do sleep 1; done -- this will ssh into node, do not want this. 
+
+#until [[ $(nodestat node001 | grep "sshd") -eq 0 ]]; 
+until nodestat node001 | grep "sshd"; 
+    do 
+	echo "node still booting, hang in there" 
+	sleep 10 
+    done
+
+echo "Nodes are in Genesis" 
 
 #nodeset nodes to appropriate image
+nodeset node001-node002 osimage=centos7-x86_64-netboot-trinity
+nodeset node003 osimage=centos7-x86_64-install-openstack
+
+sleep 2
+
+rpower node001-node003 reset
+
+echo "Go get a coffee!"
+
 
