Added initialization setup to the cv_ha_openstack script.

diff --git a/controller/rootimg/install/postscripts/cv_ha_openstack b/controller/rootimg/install/postscripts/cv_ha_openstack
--- a/controller/rootimg/install/postscripts/cv_ha_openstack
+++ b/controller/rootimg/install/postscripts/cv_ha_openstack
@@ -7,6 +7,52 @@
 ##author         : Hans Then
 ##email          : hans.then@clustervision
 
+#--------------------------------------------------------------------------
+# Setup mariadb password and initial databases
+#--------------------------------------------------------------------------
+systemctl start mariadb
+
+mysql=( mysql --protocol=socket -uroot )
+for i in {30..0}; do
+    if echo 'SELECT 1' | "${mysql[@]}" &> /dev/null; then
+        break
+    fi
+    echo 'MySQL init process in progress...'
+    sleep 1
+done
+if [ "$i" = 0 ]; then
+    echo >&2 'MySQL init process failed.'
+    exit 1
+fi
+
+"${mysql[@]}" <<-EOSQL
+    SET @@SESSION.SQL_LOG_BIN=0;
+
+    DELETE FROM mysql.user ;
+    CREATE USER 'root'@'%' IDENTIFIED BY 'system' ;
+    GRANT ALL ON *.* TO 'root'@'%' WITH GRANT OPTION ;
+    DROP DATABASE IF EXISTS test ;
+    FLUSH PRIVILEGES ;
+
+    CREATE DATABASE keystone;
+    GRANT ALL PRIVILEGES ON keystone.* TO 'keystone'@'localhost' IDENTIFIED BY 'system';
+    GRANT ALL PRIVILEGES ON keystone.* TO 'keystone'@'%'         IDENTIFIED BY 'system';
+    CREATE DATABASE glance;
+    GRANT ALL PRIVILEGES ON glance.* TO 'glance'@'localhost'     IDENTIFIED BY 'system';
+    GRANT ALL PRIVILEGES ON glance.* TO 'glance'@'%'             IDENTIFIED BY 'system';
+    CREATE DATABASE nova;
+    GRANT ALL PRIVILEGES ON nova.* TO 'nova'@'localhost'         IDENTIFIED BY 'system';
+    GRANT ALL PRIVILEGES ON nova.* TO 'nova'@'%'                 IDENTIFIED BY 'system';
+    CREATE DATABASE cinder;
+    GRANT ALL PRIVILEGES ON cinder.* TO 'cinder'@'localhost'     IDENTIFIED BY 'system';
+    GRANT ALL PRIVILEGES ON cinder.* TO 'cinder'@'%'             IDENTIFIED BY 'system';
+    FLUSH PRIVILEGES ;
+EOSQL
+
+
+#--------------------------------------------------------------------------
+# Setup pacemaker
+#--------------------------------------------------------------------------
 pcs cluster cib config
 # Setup high availability for the docker containers
 pcs -f config resource create docker systemd:docker op monitor interval="37s"
